# Generated by Django 5.1 on 2024-09-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoravailability',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='mentoravailability',
            unique_together={('mentor', 'day_of_week')},
        ),
        migrations.AddConstraint(
            model_name='mentoravailability',
            constraint=models.UniqueConstraint(fields=('mentor', 'day_of_week'), name='unique_availability_per_day'),
        ),
    ]
