# Generated by Django 5.1 on 2024-09-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_status',
        ),
        migrations.AddField(
            model_name='event',
            name='theme',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Meeting', 'Meeting'), ('Reminders', 'Reminders')], db_index=True, default='Meeting', max_length=20),
        ),
    ]
