# Generated by Django 5.1 on 2024-10-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_remove_event_event_status_event_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(blank=True, choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Meeting', 'Meeting'), ('Reminders', 'Reminders')], db_index=True, default='Personal', max_length=20, null=True),
        ),
    ]
